version: "3.4"
services:
  gumroad-verify-bot:
    image: node:slim
    user: node
    working_dir: /opt/app
    environment:
      - NODE_ENV=production
    volumes:
      - .:/opt/app
    restart: unless-stopped
    command: "node dist"
